CREATE TABLE dbo.PRODUTO (
	NU_PRODUTO numeric(5, 0) IDENTITY (1, 1) NOT NULL,
	CO_PRODUTO varchar(3) NOT NULL,
	NO_PRODUTO varchar(40) NOT NULL,
	DE_PRODUTO varchar(100),
	VR_CONSUMO_MENSAL_ESTIMADO numeric(11, 2),
	CONSTRAINT PK_PRODUTO PRIMARY KEY (NU_PRODUTO),
	CONSTRAINT AK_PRODUTO UNIQUE(CO_PRODUTO)   
);

CREATE TABLE dbo.PLANO_PRODUTO (
    NU_PLANO_PRODUTO numeric(5, 0) IDENTITY (1, 1) NOT NULL,
    NU_PRODUTO numeric(5, 0) NOT NULL,
    CO_PLANO_PRODUTO varchar(7) NOT NULL,
    NO_PLANO_PRODUTO varchar(40) NOT NULL,
    CONSTRAINT PK_PLANO_PRODUTO PRIMARY KEY (NU_PLANO_PRODUTO),
    CONSTRAINT AK_PLANO_PRODUTO UNIQUE(CO_PLANO_PRODUTO),
    CONSTRAINT FK_PLANO_PRODUTO FOREIGN KEY (NU_PRODUTO) REFERENCES dbo.PRODUTO (NU_PRODUTO)
);

CREATE TABLE dbo.SERVICO (
    NU_SERVICO numeric(9, 0) IDENTITY (1, 1) NOT NULL,
    CO_SERVICO varchar(10) NOT NULL,
    NO_SERVICO varchar(100) NOT NULL,
    NU_TIPO_COBRANCA numeric(2, 0),
    CONSTRAINT PK_SERVICO PRIMARY KEY (NU_SERVICO),
    CONSTRAINT AK_SERVICO UNIQUE(CO_SERVICO)
);

CREATE TABLE dbo.PLANO_SERVICO (
    NU_PLANO_PRODUTO numeric(5, 0) NOT NULL,
    NU_SERVICO numeric(9, 0) NOT NULL,
    VR_PLANO_SERVICO numeric(11, 2)
    CONSTRAINT PK_PPGTB004 PRIMARY KEY (NU_PLANO_PRODUTO, NU_SERVICO),
    CONSTRAINT FK_PLANO_SERVICO_PLANO_PRODUTO FOREIGN KEY (NU_PLANO_PRODUTO) REFERENCES dbo.PLANO_PRODUTO (NU_PLANO_PRODUTO),
    CONSTRAINT FK_PLANO_SERVICO_SERVICO FOREIGN KEY (NU_SERVICO) REFERENCES dbo.SERVICO (NU_SERVICO)
);

CREATE TABLE dbo.FORMA_PAGAMENTO (
    NU_FORMA_PAGAMENTO numeric(4, 0) IDENTITY (1, 1) NOT NULL,
    NO_FORMA_PAGAMENTO varchar(30) NOT NULL,
    CONSTRAINT PK_FORMA_PAGAMENTO PRIMARY KEY (NU_FORMA_PAGAMENTO),
    CONSTRAINT AK_FORMA_PAGAMENTO UNIQUE(NO_FORMA_PAGAMENTO)
 );

------------------------------ STATUS ------------------------------------
CREATE TABLE dbo.STATUS (
    NU_STATUS numeric(2, 0) IDENTITY (1, 1) NOT NULL,
    CO_STATUS varchar(3) NOT NULL,
    NO_STATUS varchar(50) NOT NULL,
    CONSTRAINT PK_STATUS PRIMARY KEY (NU_STATUS),
    CONSTRAINT AK_STATUS UNIQUE(CO_STATUS)
);

INSERT INTO dbo.STATUS(CO_STATUS, NO_STATUS) VALUES
    ('SAV', 'Salva'),
    ('DEL', 'Excluída'),
    ('EXP', 'Expirada'),
    ('BUY', 'Comprada'),
    ('ERR', 'Errada');
---------------------------------------------------------------------------
CREATE TABLE dbo.CLIENTE (
    NU_CLIENTE numeric(9, 0) IDENTITY (1, 1) NOT NULL,
	NU_DOCUMENTO_CLIENTE numeric(14,0) NOT NULL,
	NO_CLIENTE varchar(200) NOT NULL,
	VR_RENDA_MENSAL numeric(11,2) NULL,
	NU_CEP numeric(8,0) NOT NULL,
	DE_COMPLEMENTO_ENDERECO  varchar(53) NULL,
	NO_LOGRADOURO varchar(40) NULL,
	NO_MUNICIPIO varchar(35) NULL,
	NO_BAIRRO varchar(40) NULL,
	SG_UF varchar(2) NULL,
	CO_NUMERO_ENDERECO varchar(10) NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY (NU_CLIENTE),
	CONSTRAINT AK_CLIENTE UNIQUE (NU_DOCUMENTO_CLIENTE),
);

CREATE TABLE dbo.PROPOSTA (
    NU_PROPOSTA numeric(6, 0) IDENTITY (1, 1) NOT NULL,
    NU_CLIENTE numeric(9, 0) NOT NULL,
    NU_PLANO_PRODUTO numeric(5, 0) NOT NULL,
    NU_FORMA_PAGAMENTO numeric(4, 0) NOT NULL,
    QT_PRODUTO numeric(4, 0) NOT NULL,
    DD_DIA_VENCIMENTO numeric(2, 0) NOT NULL,
    CO_PROTOCOLO_PROPOSTA varchar(50),
    DT_CRIACAO_PROPOSTA date NOT NULL,
    DT_EXPIRACAO_PROPOSTA date,
    CONSTRAINT PK_PROPOSTA PRIMARY KEY (NU_PROPOSTA),
    CONSTRAINT FK_PROPOSTA_CLIENTE FOREIGN KEY (NU_CLIENTE) REFERENCES dbo.CLIENTE (NU_CLIENTE),
    CONSTRAINT FK_PROPOSTA_PLANO_PRODUTO FOREIGN KEY (NU_PLANO_PRODUTO) REFERENCES dbo.PLANO_PRODUTO  (NU_PLANO_PRODUTO),
    CONSTRAINT FK_PROPOSTA_FORMA_PAGAMENTO FOREIGN KEY (NU_FORMA_PAGAMENTO) REFERENCES dbo.FORMA_PAGAMENTO (NU_FORMA_PAGAMENTO)
);

CREATE TABLE dbo.STATUS_PROPOSTA (
    NU_STATUS numeric(2, 0) NOT NULL,
    NU_PROPOSTA numeric(6, 0),
    DH_STATUS_PROPOSTA date NOT NULL,
    DE_COMENTARIO_STATUS_PROPOSTA varchar(1000),
    CONSTRAINT PK_STATUS_PROPOSTA PRIMARY KEY (NU_PROPOSTA, NU_STATUS, DH_STATUS_PROPOSTA),
    CONSTRAINT FK_STATUS_PROPOSTA_STATUS FOREIGN KEY (NU_STATUS) REFERENCES dbo.STATUS (NU_STATUS),
    CONSTRAINT FK_STATUS_PROPOSTA_PROPOSTA FOREIGN KEY (NU_PROPOSTA) REFERENCES dbo.PROPOSTA  (NU_PROPOSTA),
    CONSTRAINT AK_STATUS_PROPOSTA UNIQUE(NU_PROPOSTA, NU_STATUS, DH_STATUS_PROPOSTA)
);